routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/preset/create', 'PresetsController@createPage')->name('preset.create.show');
Route::get('/preset/update/{preset}', 'PresetsController@updatePage')->name('preset.update.show');
Route::get('/preset/list', 'PresetsController@list')->name('preset.list');
Route::post('/preset/store', 'PresetsController@store')->name('preset.store');
Route::patch('/preset/patch/{preset}', 'PresetsController@patch')->name('preset.patch');
Route::delete('/preset/delete/{preset}', 'PresetsController@destroy')->name('preset.delete');
Route::get('/preset/getByApp/{app_id}', 'PresetsController@getByApp')->name('preset.get_by_app');

Route::get('/players', 'PlayerController@show')->name('players.show');
Route::patch('/players/{player}/add_coins', 'PlayerController@addCoins')->name('players.add_coins');

Route::get('/tutorial/{tutorial}', 'TutorialsController@show')->name('tutorial.show');
Route::get('/tutorials', 'TutorialsController@showTutorials')->name('tutorials.show');
Route::patch('/tutorial/{tutorial}', 'TutorialsController@update')->name('tutorial.patch');

app/Tutorial.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tutorial extends Model
{
    public $timestamps = false;
    protected $guarded = [];

    public function getSequenceAttribute($value)
    {
        return json_decode($value);
    }

    public function preset()
    {
        return $this->belongsTo(Preset::class);
    }
    
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/player_list.blade.php
@extends('layouts.app')
@section('content')
    <div class="container player-list-container">
        <players-table :players="{{$players}}"></players-table>
    </div>
@endsection

resources/views/preset_create_page.blade.php
@extends('layouts.app')

@section('content')
    <div class="container preset-creation-container">
        @if(session('flash'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <div>{{session('flash')}}</div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <form method="POST" id="preset-save-form" class="row" action="/preset/store" enctype="multipart/form-data">
            {{csrf_field()}}
            <div class="col">
                <table>
                    <tr>
                        <td><label>Application</label></td>
                        <td>
                            <select name="app_id" class="form-control">
                                @foreach($apps as $app)
                                    <option value="{{$app['id']}}">{{$app['title']}}</option>
                                @endforeach
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="preset-title">Preset title</label></td>
                        <td><input type="text" class="form-control" name="name" maxlength="50" id="preset-title" required value="{{old('name')}}" @input="$emit('presetTitleInput', $event)"></td>
                    </tr>
                    <tr>
                        <td><label for="preset-name">Preset name</label></td>
                        <td>
                            <preset-name old="{old: '{{old('id')}}'}"></preset-name>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="preset-files">Preset files</label></td>
                        <td><input type="file" class="form-control" name="files[]" id="preset-files" multiple required></td>
                    </tr>
                    <tr>
                        <td><label for="preset-description">Preset description</label></td>
                        <td>
                            <textarea name="description" class="form-control" id="preset-description" cols="60" rows="5">{{old('description')}}</textarea>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="preset-tags">Preset tags</label></td>
                        <td>
                            <textarea name="tag" class="form-control" id="preset-tags" cols="60" rows="2" required maxlength="50">{{old('tag')}}</textarea>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="preset-logo">Preset logo</label></td>
                        <td><input type="file" name="presetLogoName" class="form-control" id="preset-logo" accept="image/jpeg,image/png,image/gif"></td>
                    </tr>
                    <tr>
                        <td><label for="preset_price">Preset price</label></td>
                        <td><input type="number" name="cost" class="form-control" id="preset_price" value="{{old('cost')??100}}"></td>
                    </tr>
                    <tr>
                        <td><label for="preset-tutorial-url">Preset tutorial URL</label></td>
                        <td>
                            <input type="text" name="tutorial_url" class="form-control" id="preset-tutorial-url"
                                   value="{{old('tutorial_url')??'#'}}" required>
                        </td>
                    </tr>
                </table>
                <button type="submit" class="btn btn-primary">CREATE</button>
            </div>
            <div class="col">
                <pads-block
                        :colors="{{json_encode($colors)}}"
                        :pads_amount="{{$pads_amount}}"
                        :pads="{{json_encode(@$pads)}}"
                        :modes="{{json_encode($modes)}}"
                        :cut_groups="{{json_encode($cut_groups)}}"
                >
                </pads-block>
            </div>
        </form>
        @if(count($errors))
            <ul class="alert alert-danger">
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
    </div>
@endsection

resources/views/preset_list.blade.php
@extends('layouts.app')
@section('content')
    <div class="container preset-list-container">
        <presets-table :presets="{{$presets}}"></presets-table>
    </div>
@endsection

resources/views/preset_update_page.blade.php
@extends('layouts.app')

@section('content')
    <div class="container preset-creation-container">
        @if(session('flash'))
            <div class="alert alert-success" role="alert">
                <div>{{session('flash')}}</div>
            </div>
        @endif
        <form method="POST" id="preset-save-form" class="row" action="/preset/patch/{{$preset->idx}}" enctype="multipart/form-data">
            {{csrf_field()}}
            {{method_field('PATCH')}}
            <div class="col">
                <table>
                    <tr>
                        <td><label>Application</label></td>
                        <td>
                            <input type="text" class="form-control" disabled value="{{$preset->app->title}}">
                        </td>
                    </tr>
                    <tr>
                        <td><label for="preset-title">Preset title</label></td>
                        <td><input type="text" class="form-control" name="name" maxlength="50" id="preset-title" required value="{{$preset->name}}"></td>
                    </tr>
                    <tr>
                        <td><label for="preset-name">Preset name</label></td>
                        <td><input type="text" class="form-control" name="id" maxlength="50" id="preset-name" required value="{{$preset->id}}"></td>
                    </tr>
                    {{--<tr>--}}
                    {{--<td><label for="preset-files">Preset files</label></td>--}}
                    {{--<td><input type="file" class="form-control" name="files[]" id="preset-files" multiple required></td>--}}
                    {{--</tr>--}}
                    <tr>
                        <td><label for="preset-description">Preset description</label></td>
                        <td>
                            <textarea name="description" class="form-control" id="preset-description" cols="60" rows="5">{{$preset->description}}</textarea>
                        </td>
                    </tr>
                    <tr>
                        <td><label for="preset-tags">Preset tags</label></td>
                        <td>
                            <textarea name="tag" class="form-control" id="preset-tags" cols="60" rows="2" required maxlength="50">{{$preset->tag}}</textarea>
                        </td>
                    </tr>
                    {{--<tr>--}}
                    {{--<td><label for="preset-logo">Preset logo</label></td>--}}
                    {{--<td><input type="file" name="presetLogoName" class="form-control" id="preset-logo" accept="image/jpeg,image/png,image/gif"></td>--}}
                    {{--</tr>--}}
                    <tr>
                        <td><label for="preset_price">Preset price</label></td>
                        <td><input type="number" name="cost" class="form-control" id="preset_price" value="{{$preset->cost}}"></td>
                    </tr>
                    <tr>
                        <td><label for="preset-tutorial-url">Preset tutorial URL</label></td>
                        <td>
                            <input type="text" name="tutorial_url" class="form-control" id="preset-tutorial-url"
                                   value="{{$preset->tutorial_url}}" required>
                        </td>
                    </tr>
                </table>
                <button type="submit" class="btn btn-primary">UPDATE</button>
            </div>
            <div class="col">
                <pads-block
                        :colors="{{json_encode($colors)}}"
                        :pads_amount="{{$pads_amount}}"
                        :pads="{{json_encode(@$preset->files)}}"
                        :modes="{{json_encode($modes)}}"
                        :cut_groups="{{json_encode($cut_groups)}}"
                >
                </pads-block>
            </div>
        </form>
        @if(count($errors))
            <ul class="alert alert-danger">
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
    </div>
@endsection

resources/views/tutorials.blade.php
@extends('layouts.app')

@section('header')
    <script src="{{ asset('vendor/howler/howler.core.min.js') }}"></script>
@endsection

@section('content')
    <div class="container tutorials-container">
        <tutorial-top-controls ref="tutorial_top_controls"></tutorial-top-controls>
        <tutorial-track-controls></tutorial-track-controls>
        <track-table :initial_steps_amount="{{count($tutorial->sequence)}}"></track-table>
    </div>
@endsection
<script>
    window.TUTORIALS = {
        apps: {!! $apps->toJson() !!},
        steps: {!! $steps->toJson() !!},
        initial_preset_list: {!! $initial_preset_list->toJson() !!},
        app_id: {!! $tutorial->app_id !!}
    }
</script>